version: "3"

services:
  database:
    container_name: "database"
    image: postgres:14.2-alpine
    restart: "no"
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data/

  db_create:
    container_name: "db_create"
    image: doodlebob.db-create:latest
    build: .
    entrypoint: /bin/sh "./bin/doodlebob-db-create"
    restart: "no"
    env_file:
      - .env.development
    depends_on:
      - database
    links:
      - database
    volumes:
      - .:/app/
      - node-modules:/app/node_modules

volumes:
  node-modules:
