version: '3'

services:
  database:
    container_name: 'database'
    image: 'postgres:14.2-alpine'
    restart: "no"
    env_file:
      - .env.development
    ports:
      - '5432:5432'
    volumes:
      - ./database/data:/var/lib/postgresql/data/

  db_drop:
    container_name: 'db_drop'
    build: .
    entrypoint: /bin/sh './bin/doodlebob-db-drop'
    restart: "no"
    env_file:
      - .env.development
    depends_on:
      - database
    links:
      - database
    volumes:
      - .:/app/
      - /app/node_modules
