version: "3"

services:
  api:
    image: doodlebob.api.staging:${VERSION}
    command: /bin/sh -c "echo 'Running API on staging!' && pnpm run build && pnpm start"
    ports:
      - "4000:4000"
    env_file:
      - .env.staging
