version: "3"

services:
  database:
    container_name: database
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data/

  api:
    container_name: api
    entrypoint: /bin/sh "./bin/doodlebob-node-dev"
    image: doodlebob.api.development:${VERSION}
    env_file:
      - .env.development
    ports:
      - "4000:4000"
    depends_on:
      - database
    links:
      - database
