version: "3"

services:
  api:
    container_name: api
    image: doodlebob.api.base:${VERSION}
    build: .
    restart: always
    volumes:
      - .:/app/
      - node-modules:/app/node_modules

volumes:
  node-modules:
