version: "3"

services:
  api:
    container_name: api
    image: doodlebob.api.production:${VERSION}
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.90"
    #       # memory: 400M
    command: /bin/sh -c "echo 'Running API on production!' && pnpm run build && pnpm start"
    ports:
      - "4000:4000"
    env_file:
      - .env.production
